# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0829266a42acd495ba76d5ea3ff3f9cbd5fa7eb6d01dea3657b0fa134ea4711c1c024448c7e9546da0bc225176795b583c2da2aa8e0fb139b0250d4ee520d13e

test:
  secret_key_base: b61e4226b83df6ba5073a02152019dd83ef0e44dd9e9625de6225556ecc56c93cc3e6a423b237949b9f3000024db3be37927fcb3176052c2c28c827eff1e69f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
